Repository james-n-007/cf, pull requests merged in 2020-05, with the labels that each got.

#2 abcd
  266A.cxx
  546a.cxx
Labels: bug

#3 Create dfs2w.cxx
  dfs2.cxx
Labels: enhancement

#7 Create djikstra.cxx
  djikstra.cxx
Labels: documentation, enhancements, good first issue
